version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.21.3
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - rag-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - weaviate
    networks:
      - rag-network
    deploy:
      resources:
        reservations: {}
          # devices:
          #   - driver: nvidia
          #     count: all
          #     capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      - backend
    networks:
      - rag-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  rag-network:
    driver: bridge

volumes:
  weaviate_data:
